0>Employee.cs(17,20): Warning CS0114 : 'Employee.PhoneNumber' hides inherited member 'IdentityUser<int>.PhoneNumber'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword. 0>HrDbContext.cs(83,13): Warning CS0618 : 'RelationalEntityTypeBuilderExtensions.HasCheckConstraint<TEntity>(EntityTypeBuilder<TEntity>, string, string?)' is obsolete: 'Configure this using ToTable(t => t.HasCheckConstraint()) instead.' 0>AbsenceController.cs(145,26): Warning CS0168 : The variable 'ex' is declared but never used 0>AbsenceController.cs(173,26): Warning CS0168 : The variable 'ex' is declared but never used 0>AbsenceController.cs(198,26): Warning CS0168 : The variable 'ex' is declared but never used 0>EmployeeController.cs(128,27): Error CS1503 : Argument 1: cannot convert from '<anonymous type: string message>' to 'string' 0>Employee.cs(17,20): Warning CS0114 : 'Employee.PhoneNumber' hides inherited member 'IdentityUser<int>.PhoneNumber'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword. 0>HrDbContext.cs(83,13): Warning CS0618 : 'RelationalEntityTypeBuilderExtensions.HasCheckConstraint<TEntity>(EntityTypeBuilder<TEntity>, string, string?)' is obsolete: 'Configure this using ToTable(t => t.HasCheckConstraint()) instead.' 0>AbsenceController.cs(145,26): Warning CS0168 : The variable 'ex' is declared but never used 0>AbsenceController.cs(173,26): Warning CS0168 : The variable 'ex' is declared but never used 0>AbsenceController.cs(198,26): Warning CS0168 : The variable 'ex' is declared but never used 0>EmployeeController.cs(128,27): Error CS1503 : Argument 1: cannot convert from '<anonymous type: string message>' to 'string' 0>AuthService.cs(133,31): Warning CS1998 : This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread. 0>------- Finished building project: HrAPI. Succeeded: False. Errors: 1. Warnings: 6 Build completed in 00:00:04.345
clear0>AuthService.cs(133,31): Warning CS1998 : This async method lacks 'await' operators and will run synchronously. Consider using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.
0>------- Finished building project: HrAPI. Succeeded: False. Errors: 1. Warnings: 6
Build completed in 00:00:04.345